import numpy as np 
Net={
        # structure data
        "bus": [('name', np.dtype(object)),
                ('type', np.dtype(object)),
                ('zone', np.dtype(object)),
                ('in_service', 'bool'), ],
        "load": [("name", np.dtype(object)),
                 ('time', 'f8'),
                 ("bus", "u4"),
                 ("p_w", "f8"),
                 ("scaling", "f8"),
                 ("in_service", 'bool'),
                 ("type", np.dtype(object))],
        "house": [("name", np.dtype(object)),
                 ('time', 'f8'),
                 ("bus", "u4"),
                 ("p_w", "f8"),
                 ("pv_w",'bool'),
                 ("st_w",'bool'),
                 ("scaling", "f8"),
                 ("in_service", 'bool'),
                 ("type", np.dtype(object))],
        "housepv": [("name", np.dtype(object)),
                 ("pv", 'bool'),
                 ('time', 'f8'),
                 ("bus", "u4"),
                 ("p_w", "f8"),
                 ("pv_w","f8"),
                 ("st_w","f8"),
                 ("scaling", "f8"),
                 ("in_service", 'bool'),
                 ("type", np.dtype(object))],
        "housepvb": [("name", np.dtype(object)),
                 ("pv", np.dtype(object)),
                 ("st", np.dtype(object)),
                 ('time', 'f8'),
                 ("bus", "u4"),
                 ("p_w", "f8"),
                 ("pv_w","f8"),
                 ("st_w","f8"),
                 ("scaling", "f8"),
                 ("in_service", 'bool'),
                 ("type", np.dtype(object))],
        "gen": [("name", np.dtype(object)),
                 ('time', 'f8'),
                 ("bus", "i8"),
                 ("p_w", "f8"),
                 ("scaling", "f8"),
                 ("in_service", 'bool'),
                 ("type", np.dtype(object)),
                 ("current_source", "bool")],
        "storage": [("name", np.dtype(object)),
                 ('time', 'f8'),
                 ("bus", "i8"),
                 ("max_p_w", "f8"),
                 ("start_SOC", "f8"),
                 ("end_SOC", "f8"),
                 ("minimum_p_w","f8"),
                 ("scaling", "f8"),
                 ("in_service", 'bool'),
                 ("type", np.dtype(object)),
                 ("current_source", "bool")],
        "pv": [("name", np.dtype(object)),
                ('time', 'f8'),
                ("bus", "i8"),
                ("p_w", "f8"),
                ("scaling", "f8"),
                ("in_service", 'bool'),
                ("type", np.dtype(object)),
                ("current_source", "bool")],
        "switch": [("bus", "i8"),
                   ("element", "i8"),
                   ("et", np.dtype(object)),
                   ("type", np.dtype(object)),
                   ("closed", "bool"),
                   ("name", np.dtype(object)),
                   ("z_ohm", "f8")],
        "ext_grid": [("name", np.dtype(object)),
                     ('time', 'f8'),
                     ("bus", "u4"),
                     ("max_p_mw", "f8"),
                     ("in_service", 'bool')],
        "line": [("name", np.dtype(object)),
                 ("from_bus", "u4"),
                 ("to_bus", "u4"),
                 ("length_km", "f8"),
                 ("parallel", "u4"),
                 ("type", np.dtype(object)),
                 ("in_service", 'bool')],
        "trafo": [("name", np.dtype(object)),
                ("from_bus", "u4"),
                ("to_bus", "u4"),
                ("type", np.dtype(object)),
                ("in_service", 'bool')],
        "measurement": [("name", np.dtype(object)),
                        ('time', 'f8'),
                        ("measurement_type", np.dtype(object)),
                        ("element_type", np.dtype(object)),
                        ("element", "uint32"),
                        ("value", "float64"),
                        ("std_dev", "float64"),
                        ("side", np.dtype(object))],
        "pwl_cost": [("power_type", np.dtype(object)),
                     ('time', 'f8'),
                     ("element", np.dtype(object)),
                     ("et", np.dtype(object)),
                     ("points", np.dtype(object))],
        "poly_cost": [("element", np.dtype(object)),
                      ('time', 'f8'),
                      ("et", np.dtype(object)),
                      ("cp0_eur", np.dtype("f8")),
                      ("cp1_eur_per_mw", np.dtype("f8")),
                      ("cp2_eur_per_mw2", np.dtype("f8")),
                      ("cq0_eur", np.dtype("f8")),
                      ("cq1_eur_per_mvar", np.dtype("f8")),
                      ("cq2_eur_per_mvar2", np.dtype("f8"))
                      ],
        # geodata
        "line_geodata": [("coords", np.dtype(object))],
        "bus_geodata": [("x", "f8"), ("y", "f8"), ("coords", np.dtype(object))],
        # result tables

       
        "_empty_res_house": [("name", np.dtype(object)),
                            ("time", "f8"),
                            ('p_w', 'f8')],
        "_empty_res_housepv": [("name", np.dtype(object)),
                            ("time", "f8"),
                            ('p_w', 'f8'),
                            ('pv',"f8"),
                            ('pv_2ld',"f8"),
                            ('pv_sell',"f8")],
        "_empty_res_housepvb": [("name", np.dtype(object)),
                            ("time", "f8"),
                            ('p_w', 'f8'),
                            ('pv',"f8"),
                            ('pv_2st',"f8"),
                            ('pv_2ld',"f8"),
                            ('pv_sell',"f8"),
                            ("SOC", "f8"),
                            ("st_charge", "f8"),
                            ("st_discharge", "f8")],
        "_empty_res_pv": [("name", np.dtype(object)),
                            ('time', 'f8'),
                            ("use_2st", "f8"),
                            ("use_2ld", "f8"),
                            ("sell", "f8")],
        "_empty_res_storage": [("name", np.dtype(object)),
                                ("time", "f8"),
                               ('SOC', 'f8'),
                               ('pv_charge', 'f8'),
                               ('grid_charge', 'f8'),
                               ('load_discharge', 'f8')],
        "_empty_res_load": [("name", np.dtype(object)),
                                ("time", "f8"),
                                ('p_w', 'f8'),
                                ('st_p_w', 'f8'),
                                ('pv_p_w', 'f8'),
                                ('grid_p_w', 'f8')],
        "_empty_res_gen": [("time", "f8"),
                           ('produce_p_w', 'f8'),
                           ("balance_p_w", "f8"),
                           ("use_p_w", "f8")], 
                           
        "_empty_res_storage_SOC": [("name", np.dtype(object)),
                                ("Hour-0", "f8")],

        "_empty_res_ext_grid": [("name", np.dtype(object)),
                                ("Hour-0", "f8"),("Hour-1", "f8"),("Hour-2", "f8"),("Hour-3", "f8"),("Hour-4", "f8"),("Hour-5", "f8"),("Hour-6", "f8"),
                                   ("Hour-7", "f8"),("Hour-8", "f8"),("Hour-9", "f8"),("Hour-10", "f8"),("Hour-11", "f8"),("Hour-12", "f8"),("Hour-13", "f8"),
                                    ("Hour-14", "f8"),("Hour-15", "f8"),("Hour-16", "f8"),("Hour-17", "f8"),("Hour-18", "f8"),("Hour-19", "f8"),("Hour-20", "f8"),
                                    ("Hour-21", "f8"),("Hour-22", "f8"),("Hour-23", "f8")],
        "_empty_res_load_data": [("name", np.dtype(object)),
                                ("Hour-0", "f8"),("Hour-1", "f8"),("Hour-2", "f8"),("Hour-3", "f8"),("Hour-4", "f8"),("Hour-5", "f8"),("Hour-6", "f8"),
                                   ("Hour-7", "f8"),("Hour-8", "f8"),("Hour-9", "f8"),("Hour-10", "f8"),("Hour-11", "f8"),("Hour-12", "f8"),("Hour-13", "f8"),
                                    ("Hour-14", "f8"),("Hour-15", "f8"),("Hour-16", "f8"),("Hour-17", "f8"),("Hour-18", "f8"),("Hour-19", "f8"),("Hour-20", "f8"),
                                    ("Hour-21", "f8"),("Hour-22", "f8"),("Hour-23", "f8")],
        "_empty_res_load_4grid": [("name", np.dtype(object)),
                                ("Hour-0", "f8"),("Hour-1", "f8"),("Hour-2", "f8"),("Hour-3", "f8"),("Hour-4", "f8"),("Hour-5", "f8"),("Hour-6", "f8"),
                                   ("Hour-7", "f8"),("Hour-8", "f8"),("Hour-9", "f8"),("Hour-10", "f8"),("Hour-11", "f8"),("Hour-12", "f8"),("Hour-13", "f8"),
                                    ("Hour-14", "f8"),("Hour-15", "f8"),("Hour-16", "f8"),("Hour-17", "f8"),("Hour-18", "f8"),("Hour-19", "f8"),("Hour-20", "f8"),
                                    ("Hour-21", "f8"),("Hour-22", "f8"),("Hour-23", "f8")],
        "_empty_res_load_4pv": [("name", np.dtype(object)),
                                ("Hour-0", "f8"),("Hour-1", "f8"),("Hour-2", "f8"),("Hour-3", "f8"),("Hour-4", "f8"),("Hour-5", "f8"),("Hour-6", "f8"),
                                   ("Hour-7", "f8"),("Hour-8", "f8"),("Hour-9", "f8"),("Hour-10", "f8"),("Hour-11", "f8"),("Hour-12", "f8"),("Hour-13", "f8"),
                                    ("Hour-14", "f8"),("Hour-15", "f8"),("Hour-16", "f8"),("Hour-17", "f8"),("Hour-18", "f8"),("Hour-19", "f8"),("Hour-20", "f8"),
                                    ("Hour-21", "f8"),("Hour-22", "f8"),("Hour-23", "f8")],
         "_empty_res_load_4st": [("name", np.dtype(object)),
                                ("Hour-0", "f8"),("Hour-1", "f8"),("Hour-2", "f8"),("Hour-3", "f8"),("Hour-4", "f8"),("Hour-5", "f8"),("Hour-6", "f8"),
                                   ("Hour-7", "f8"),("Hour-8", "f8"),("Hour-9", "f8"),("Hour-10", "f8"),("Hour-11", "f8"),("Hour-12", "f8"),("Hour-13", "f8"),
                                    ("Hour-14", "f8"),("Hour-15", "f8"),("Hour-16", "f8"),("Hour-17", "f8"),("Hour-18", "f8"),("Hour-19", "f8"),("Hour-20", "f8"),
                                    ("Hour-21", "f8"),("Hour-22", "f8"),("Hour-23", "f8")],
        "_empty_res_ext_grid_buy": [("name", np.dtype(object)),
                                    ("Hour-0", "f8"),("Hour-1", "f8"),("Hour-2", "f8"),("Hour-3", "f8"),("Hour-4", "f8"),("Hour-5", "f8"),("Hour-6", "f8"),
                                   ("Hour-7", "f8"),("Hour-8", "f8"),("Hour-9", "f8"),("Hour-10", "f8"),("Hour-11", "f8"),("Hour-12", "f8"),("Hour-13", "f8"),
                                    ("Hour-14", "f8"),("Hour-15", "f8"),("Hour-16", "f8"),("Hour-17", "f8"),("Hour-18", "f8"),("Hour-19", "f8"),("Hour-20", "f8"),
                                    ("Hour-21", "f8"),("Hour-22", "f8"),("Hour-23", "f8")],
        "_empty_res_ext_grid_balance": [("name", np.dtype(object)),
                                    ("Hour-0", "f8"),("Hour-1", "f8"),("Hour-2", "f8"),("Hour-3", "f8"),("Hour-4", "f8"),("Hour-5", "f8"),("Hour-6", "f8"),
                                   ("Hour-7", "f8"),("Hour-8", "f8"),("Hour-9", "f8"),("Hour-10", "f8"),("Hour-11", "f8"),("Hour-12", "f8"),("Hour-13", "f8"),
                                    ("Hour-14", "f8"),("Hour-15", "f8"),("Hour-16", "f8"),("Hour-17", "f8"),("Hour-18", "f8"),("Hour-19", "f8"),("Hour-20", "f8"),
                                    ("Hour-21", "f8"),("Hour-22", "f8"),("Hour-23", "f8")],
        "_empty_res_ext_grid_2st": [("name", np.dtype(object)),
                                    ("Hour-0", "f8"),("Hour-1", "f8"),("Hour-2", "f8"),("Hour-3", "f8"),("Hour-4", "f8"),("Hour-5", "f8"),("Hour-6", "f8"),
                                   ("Hour-7", "f8"),("Hour-8", "f8"),("Hour-9", "f8"),("Hour-10", "f8"),("Hour-11", "f8"),("Hour-12", "f8"),("Hour-13", "f8"),
                                    ("Hour-14", "f8"),("Hour-15", "f8"),("Hour-16", "f8"),("Hour-17", "f8"),("Hour-18", "f8"),("Hour-19", "f8"),("Hour-20", "f8"),
                                    ("Hour-21", "f8"),("Hour-22", "f8"),("Hour-23", "f8")],
        "_empty_res_ext_grid_2ld": [("name", np.dtype(object)),
                                    ("Hour-0", "f8"),("Hour-1", "f8"),("Hour-2", "f8"),("Hour-3", "f8"),("Hour-4", "f8"),("Hour-5", "f8"),("Hour-6", "f8"),
                                   ("Hour-7", "f8"),("Hour-8", "f8"),("Hour-9", "f8"),("Hour-10", "f8"),("Hour-11", "f8"),("Hour-12", "f8"),("Hour-13", "f8"),
                                    ("Hour-14", "f8"),("Hour-15", "f8"),("Hour-16", "f8"),("Hour-17", "f8"),("Hour-18", "f8"),("Hour-19", "f8"),("Hour-20", "f8"),
                                    ("Hour-21", "f8"),("Hour-22", "f8"),("Hour-23", "f8")],
        "_empty_res_pv_production": [("name", np.dtype(object)),
                                ("Hour-0", "f8"),("Hour-1", "f8"),("Hour-2", "f8"),("Hour-3", "f8"),("Hour-4", "f8"),("Hour-5", "f8"),("Hour-6", "f8"),
                                   ("Hour-7", "f8"),("Hour-8", "f8"),("Hour-9", "f8"),("Hour-10", "f8"),("Hour-11", "f8"),("Hour-12", "f8"),("Hour-13", "f8"),
                                    ("Hour-14", "f8"),("Hour-15", "f8"),("Hour-16", "f8"),("Hour-17", "f8"),("Hour-18", "f8"),("Hour-19", "f8"),("Hour-20", "f8"),
                                    ("Hour-21", "f8"),("Hour-22", "f8"),("Hour-23", "f8")],
        "_empty_res_pv_2st": [("name", np.dtype(object)),
                                ("Hour-0", "f8"),("Hour-1", "f8"),("Hour-2", "f8"),("Hour-3", "f8"),("Hour-4", "f8"),("Hour-5", "f8"),("Hour-6", "f8"),
                                   ("Hour-7", "f8"),("Hour-8", "f8"),("Hour-9", "f8"),("Hour-10", "f8"),("Hour-11", "f8"),("Hour-12", "f8"),("Hour-13", "f8"),
                                    ("Hour-14", "f8"),("Hour-15", "f8"),("Hour-16", "f8"),("Hour-17", "f8"),("Hour-18", "f8"),("Hour-19", "f8"),("Hour-20", "f8"),
                                    ("Hour-21", "f8"),("Hour-22", "f8"),("Hour-23", "f8")],
        "_empty_res_pv_2ld": [("name", np.dtype(object)),
                                ("Hour-0", "f8"),("Hour-1", "f8"),("Hour-2", "f8"),("Hour-3", "f8"),("Hour-4", "f8"),("Hour-5", "f8"),("Hour-6", "f8"),
                                   ("Hour-7", "f8"),("Hour-8", "f8"),("Hour-9", "f8"),("Hour-10", "f8"),("Hour-11", "f8"),("Hour-12", "f8"),("Hour-13", "f8"),
                                    ("Hour-14", "f8"),("Hour-15", "f8"),("Hour-16", "f8"),("Hour-17", "f8"),("Hour-18", "f8"),("Hour-19", "f8"),("Hour-20", "f8"),
                                    ("Hour-21", "f8"),("Hour-22", "f8"),("Hour-23", "f8")],
        "_empty_res_pv_2sell": [("name", np.dtype(object)),
                                ("Hour-0", "f8"),("Hour-1", "f8"),("Hour-2", "f8"),("Hour-3", "f8"),("Hour-4", "f8"),("Hour-5", "f8"),("Hour-6", "f8"),
                                   ("Hour-7", "f8"),("Hour-8", "f8"),("Hour-9", "f8"),("Hour-10", "f8"),("Hour-11", "f8"),("Hour-12", "f8"),("Hour-13", "f8"),
                                    ("Hour-14", "f8"),("Hour-15", "f8"),("Hour-16", "f8"),("Hour-17", "f8"),("Hour-18", "f8"),("Hour-19", "f8"),("Hour-20", "f8"),
                                    ("Hour-21", "f8"),("Hour-22", "f8"),("Hour-23", "f8")],
        "_empty_res_storage_charge": [("name", np.dtype(object)),
                                ("Hour-0", "f8"),("Hour-1", "f8"),("Hour-2", "f8"),("Hour-3", "f8"),("Hour-4", "f8"),("Hour-5", "f8"),("Hour-6", "f8"),
                                   ("Hour-7", "f8"),("Hour-8", "f8"),("Hour-9", "f8"),("Hour-10", "f8"),("Hour-11", "f8"),("Hour-12", "f8"),("Hour-13", "f8"),
                                    ("Hour-14", "f8"),("Hour-15", "f8"),("Hour-16", "f8"),("Hour-17", "f8"),("Hour-18", "f8"),("Hour-19", "f8"),("Hour-20", "f8"),
                                    ("Hour-21", "f8"),("Hour-22", "f8"),("Hour-23", "f8")],
        "_empty_res_storage_discharge": [("name", np.dtype(object)),
                                ("Hour-0", "f8"),("Hour-1", "f8"),("Hour-2", "f8"),("Hour-3", "f8"),("Hour-4", "f8"),("Hour-5", "f8"),("Hour-6", "f8"),
                                   ("Hour-7", "f8"),("Hour-8", "f8"),("Hour-9", "f8"),("Hour-10", "f8"),("Hour-11", "f8"),("Hour-12", "f8"),("Hour-13", "f8"),
                                    ("Hour-14", "f8"),("Hour-15", "f8"),("Hour-16", "f8"),("Hour-17", "f8"),("Hour-18", "f8"),("Hour-19", "f8"),("Hour-20", "f8"),
                                    ("Hour-21", "f8"),("Hour-22", "f8"),("Hour-23", "f8")],
        "_empty_res_storage_N_SOC": [("name", np.dtype(object)),
                                ("Hour-0", "f8"),("Hour-1", "f8"),("Hour-2", "f8"),("Hour-3", "f8"),("Hour-4", "f8"),("Hour-5", "f8"),("Hour-6", "f8"),
                                   ("Hour-7", "f8"),("Hour-8", "f8"),("Hour-9", "f8"),("Hour-10", "f8"),("Hour-11", "f8"),("Hour-12", "f8"),("Hour-13", "f8"),
                                    ("Hour-14", "f8"),("Hour-15", "f8"),("Hour-16", "f8"),("Hour-17", "f8"),("Hour-18", "f8"),("Hour-19", "f8"),("Hour-20", "f8"),
                                    ("Hour-21", "f8"),("Hour-22", "f8"),("Hour-23", "f8")], 

        # internal
        "_ppc": None,
        "_is_elements": None,
        "_pd2ppc_lookups": {"bus": None,
                            "ext_grid": None,
                            "gen": None},
        "converged": False,
        "name": "",
        "f_hz": 50.,
        "sn_mva": 1.
    }
storagetypes = {
        # 
        # Low Voltage
        "battery_4kwh":
        {"max_p_w": 5000,
        "minimum_p_w":800,
            "max_discharge": 1000,
            "max_charge": 1000},
        "battery_5kwh":
        {"max_p_w": 5500,
        "minimum_p_w":500,
            "max_discharge": 1000,
            "max_charge": 1000},
        "battery_6kwh":
        {"max_p_w": 6000,
        "minimum_p_w":1200,
            "max_discharge": 1000,
            "max_charge": 1000}
}

pvtypes = {
        # 
        # Low Voltage
        "pv_2kw":
        {"max_p_w": 1900,
        "min_p_w": 0},
        "pv_3kw":
        {"max_p_w": 2900,
        "min_p_w": 0},
        "pv_4kw":
        {"max_p_w": 3900,
        "min_p_w": 0}
}
# "production":{"Hour-0":0,"Hour-1":0,"Hour-2":0,"Hour-3":0,"Hour-4":0,"Hour-5":20,"Hour-6":100,
#         "Hour-7":300,"Hour-8":600,"Hour-9":1000,"Hour-10":1400,"Hour-11":1600,"Hour-12":1800,"Hour-13":1600,
#         "Hour-14":1450,"Hour-15":1000,"Hour-16":800,"Hour-17":500,"Hour-18":150,"Hour-19":20,"Hour-20":0,
#         "Hour-21":0,"Hour-22":0,"Hour-23":0}