
from network import *
net=Network(new=True)
bus1=net.create_bus(name="bus1")
bus2=net.create_bus(name="bus2")
bus3=net.create_bus(name="bus3")
bus4=net.create_bus(name="bus4")
bus5=net.create_bus(name="bus1")
bus6=net.create_bus(name="bus2")
bus7=net.create_bus(name="bus3")
bus8=net.create_bus(name="bus4")
bus9=net.create_bus(name="bus4")
bus10=net.create_bus(name="bus1")
bus11=net.create_bus(name="bus2")

_,h1=net.create_housepv(bus2,p_w=400,pv="pv_2kw")
_,h2=net.create_housepv(bus3,p_w=400,pv="pv_2kw")
_,h3=net.create_housepvb(bus4,p_w=400,pv="pv_2kw",storage="battery_4kwh")
_,h4=net.create_housepv(bus5,p_w=400,pv="pv_2kw")
_,h5=net.create_housepv(bus6,p_w=400,pv="pv_2kw")
_,h6=net.create_housepvb(bus7,p_w=400,pv="pv_2kw",storage="battery_4kwh")
_,h7=net.create_housepvb(bus8,p_w=400,pv="pv_2kw",storage="battery_4kwh")
_,h8=net.create_housepv(bus9,p_w=400,pv="pv_2kw")
_,h9=net.create_housepvb(bus10,p_w=400,pv="pv_2kw",storage="battery_4kwh")
_,h10=net.create_housepvb(bus11,p_w=400,pv="pv_2kw",storage="battery_4kwh")
net.create_ext_grid(bus1,max_p_mw=20)
net.create_line(bus1,bus2,length_km=1)
net.create_line(bus2,bus3,length_km=1)
net.create_line(bus3,bus4,length_km=1)
net.create_line(bus1,bus5,length_km=1,direct="down",theta=-90)
net.create_line(bus5,bus6,length_km=1)
net.create_line(bus6,bus7,length_km=1)
net.create_line(bus7,bus8,length_km=1)
net.create_line(bus5,bus9,length_km=1,direct="down",theta=-90)
net.create_line(bus9,bus10,length_km=1)
net.create_line(bus10,bus11,length_km=1)

#definde group for learning
print(net.net)
group1=[h1,h2,h3]
group2=[h4,h5,h6,h7]
group3=[h8,h9,h10]
data=Data_intialize(net.net,'model_data.xlsx',[group1,group2,group3])
ls=Learn_set(net.net,[group1,group2,group3])
create_schem(net)