from network import *
net=Network(new=True)
bus1=net.create_bus(name="bus1")
bus2=net.create_bus(name="bus2")
bus3=net.create_bus(name="bus3")
#net.create_house(bus1,p_w=400)
net.create_housepv(bus1,p_w=400,pv="pv_2kw")
net.create_housepv(bus2,p_w=400,pv="pv_2kw")
net.create_housepvb(bus3,p_w=400,pv="pv_2kw",storage="battery_4kwh")
# net.create_house(bus3,p_w=400)
net.create_ext_grid(bus1,max_p_mw=20)
net.create_line(bus1,bus2,length_km=1)
net.create_line(bus2,bus3,length_km=1)
#net.create_load(bus2,p_w=20)
create_schem(net)